# -*- coding: utf-8 -*-
"""task1_Lstm_Autoencoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qECcQ712gzJseUnPT4_DkBxM7osuk7LO
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pretty_midi

import os

folders = [
    '/content/drive/MyDrive/music-project/outputs/generated_midis',
    '/content/drive/MyDrive/music-project/outputs/plots',
    '/content/drive/MyDrive/music-project/outputs/survey_results/tokens',
]
for f in folders:
    os.makedirs(f, exist_ok=True)

print("All folders created!")

import zipfile, os

zip_path = '/content/drive/MyDrive/Music Project/maestro-v3.0.0-midi.zip'
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall('/content/maestro/')
print("CSV exists:", os.path.exists('/content/maestro/maestro-v3.0.0/maestro-v3.0.0.csv'))

exec(open('/content/drive/MyDrive/Music Project/task1.py').read())
print("Task 1 code loaded!")

import torch

CSV_PATH  = '/content/maestro/maestro-v3.0.0/maestro-v3.0.0.csv'
MIDI_ROOT = '/content/maestro/maestro-v3.0.0'
OUT_DIR   = '/content/drive/MyDrive/music-project/outputs/generated_midis'
PLOT_DIR  = '/content/drive/MyDrive/music-project/outputs/plots'
DEVICE    = 'cuda' if torch.cuda.is_available() else 'cpu'

print(f"GPU available: {torch.cuda.is_available()}")
print(f"Device: {DEVICE}")

from torch.utils.data import DataLoader

train_ds = MAESTRODataset(CSV_PATH, MIDI_ROOT, split='train')
val_ds   = MAESTRODataset(CSV_PATH, MIDI_ROOT, split='validation')

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=0)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=0)

print("Dataset ready!")

LATENT = 64
EPOCHS = 50

model = LSTMAutoencoder(
    input_dim  = PIANO_KEYS,
    hidden_dim = 256,
    latent_dim = LATENT,
    seq_len    = SEQ_LEN
)

print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")
print("Starting training...")

train_losses, val_losses = train(
    model, train_loader, val_loader,
    epochs=EPOCHS, device=DEVICE
)


torch.save(model.state_dict(),
           '/content/drive/MyDrive/music-project/outputs/ae_weights.pt')
print("Model saved to Drive!")

plot_loss(train_losses, val_losses,
          save_path=f'{PLOT_DIR}/loss_curve_task1.png')
print("Plot saved to Drive!")

print("Generating 5 MIDI samples...")

for i in range(5):
    out_path = f'{OUT_DIR}/task1_sample_{i+1}.mid'
    n = generate_midi(
        model,
        latent_dim = LATENT,
        threshold  = 0.2,
        out_path   = out_path,
        device     = DEVICE
    )
    print(f"Sample {i+1}: {n} notes generated")

print("All 5 samples saved to Drive!")

print("TASK 1 METRICS")
for i in range(1, 6):
    p = f'{OUT_DIR}/task1_sample_{i}.mid'
    if os.path.exists(p):
        rd = rhythm_diversity(p)
        rr = repetition_ratio(p)
        print(f"Sample {i}: Rhythm Diversity = {rd:.3f} | Repetition Ratio = {rr:.3f}")