# -*- coding: utf-8 -*-
"""task2_Vae.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7oxFvkeqva2_klplGe5tjQ-Vuvuoj2A
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pretty_midi

import os

folders = [
    '/content/drive/MyDrive/music-project/outputs/generated_midis',
    '/content/drive/MyDrive/music-project/outputs/plots',
    '/content/drive/MyDrive/music-project/outputs/survey_results/tokens',
]
for f in folders:
    os.makedirs(f, exist_ok=True)

print("All folders created!")

import zipfile, os

zip_path = '/content/drive/MyDrive/Music Project/maestro-v3.0.0-midi.zip'

print("Extracting dataset...")
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall('/content/maestro/')

exec(open('/content/drive/MyDrive/Music Project/task2.py').read())
print("Task 2 code loaded!")

import torch

CSV_PATH  = '/content/maestro/maestro-v3.0.0/maestro-v3.0.0.csv'
MIDI_ROOT = '/content/maestro/maestro-v3.0.0'
OUT_DIR   = '/content/drive/MyDrive/music-project/outputs/generated_midis'
PLOT_DIR  = '/content/drive/MyDrive/music-project/outputs/plots'
DEVICE    = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {DEVICE}")

from torch.utils.data import DataLoader

print("Loading dataset...")
train_ds = MAESTROMultiGenreDataset(CSV_PATH, MIDI_ROOT, split='train')
val_ds   = MAESTROMultiGenreDataset(CSV_PATH, MIDI_ROOT, split='validation')

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=0)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=0)
print("Dataset ready!")

LATENT        = 32
EPOCHS        = 5
WARMUP_EPOCHS = 2

model = MusicVAE(input_dim=PIANO_KEYS, hidden_dim=128,
                 latent_dim=LATENT, seq_len=SEQ_LEN)

print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
print("Training...")

history = train(model, train_loader, val_loader,
                epochs=EPOCHS, warmup_epochs=WARMUP_EPOCHS,
                device=DEVICE)

torch.save(model.state_dict(),
           '/content/drive/MyDrive/music-project/outputs/vae_weights.pt')
print("Model saved!")

plot_losses(history, save_path=f'{PLOT_DIR}/loss_curve_task2.png')
print("Plot saved!")

generate_samples(model, n=4, threshold=0.2,
                 out_dir=OUT_DIR, device=DEVICE)
print("4 samples done!")

latent_interpolation(model, n_steps=8, threshold=0.2,
                     out_dir=OUT_DIR, device=DEVICE)
print("Interpolation done!")

print("TASK 2 METRICS")
for i in range(1, 9):
    p = f'{OUT_DIR}/task2_sample_{i}.mid'
    if os.path.exists(p):
        rd = rhythm_diversity(p)
        rr = repetition_ratio(p)
        print(f"Sample {i}: Rhythm Div={rd:.3f} | Rep Ratio={rr:.3f}")