# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSvApWILzeYV2CfoOp6M5mwOWlAseihn
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pretty_midi
import pandas as pd
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


BASE      = '/content/drive/MyDrive/music-project'
CSV_PATH  = '/content/maestro/maestro-v3.0.0/maestro-v3.0.0.csv'
MIDI_ROOT = '/content/maestro/maestro-v3.0.0'
OUT_DIR   = f'{BASE}/outputs/generated_midis'
PLOT_DIR  = f'{BASE}/outputs/plots'
WEIGHTS   = f'{BASE}/outputs/vae_weights.pt'


PIANO_MIN          = 21
PIANO_MAX          = 108
PIANO_KEYS         = 88
FS                 = 16
SEQ_LEN            = 64    # ↓ from 128  → 2× faster per step
SPARSITY_THRESHOLD = 0.02
MAX_FILES          = 200   # cap files loaded per split → fast dataset build

EPOCHS        = 5
WARMUP_EPOCHS = 2          # β=0 for first 2 epochs, then ramps to 1
LATENT        = 64
HIDDEN_DIM    = 128        # ↓ from 256  → smaller model, faster
BATCH_SIZE    = 64         # ↑ from 32   → better GPU utilisation
NUM_WORKERS   = 2          # parallel data loading
DEVICE        = 'cuda' if torch.cuda.is_available() else 'cpu'


BAROQUE_COMPOSERS   = ['Bach', 'Handel', 'Scarlatti', 'Vivaldi', 'Telemann']
CLASSICAL_COMPOSERS = ['Mozart', 'Haydn', 'Clementi', 'Dussek']
ROMANTIC_COMPOSERS  = ['Chopin', 'Liszt', 'Brahms', 'Schumann', 'Schubert',
                        'Mendelssohn', 'Tchaikovsky']
MODERN_COMPOSERS    = ['Debussy', 'Ravel', 'Scriabin', 'Rachmaninoff',
                        'Prokofiev', 'Bartók', 'Beethoven']

GENRE_NAMES = {0: 'Baroque', 1: 'Classical', 2: 'Romantic', 3: 'Modern'}
NUM_GENRES  = 4


def composer_to_genre(composer_name: str) -> int:
    name = str(composer_name)
    for c in BAROQUE_COMPOSERS:
        if c.lower() in name.lower(): return 0
    for c in CLASSICAL_COMPOSERS:
        if c.lower() in name.lower(): return 1
    for c in ROMANTIC_COMPOSERS:
        if c.lower() in name.lower(): return 2
    return 3


class MAESTROMultiGenreDataset(Dataset):
    def __init__(self, csv_path: str, midi_root: str, split: str = 'train',
                 seq_len: int = SEQ_LEN, fs: int = FS, max_files: int = MAX_FILES):
        self.seq_len = seq_len
        self.samples = []
        self.labels  = []

        df = pd.read_csv(csv_path)
        df = df[df['split'] == split].copy()


        df = df.head(max_files)

        if 'canonical_composer' not in df.columns:
            print("WARNING: 'canonical_composer' column not found — all genres → Modern")
            df['canonical_composer'] = ''
        else:
            df['canonical_composer'] = df['canonical_composer'].fillna('')

        for _, row in df.iterrows():
            midi_path = os.path.join(midi_root, row['midi_filename'])
            if not os.path.exists(midi_path):
                continue

            genre = composer_to_genre(row['canonical_composer'])
            try:
                pm   = pretty_midi.PrettyMIDI(midi_path)
                roll = pm.get_piano_roll(fs=fs)[PIANO_MIN:PIANO_MAX + 1, :].T
                roll = (roll > 0).astype(np.float32)
                for start in range(0, len(roll) - seq_len, seq_len):
                    window = roll[start:start + seq_len]
                    if window.mean() >= SPARSITY_THRESHOLD:
                        self.samples.append(window)
                        self.labels.append(genre)
            except Exception:
                continue

        genre_counts = {}
        for lbl in self.labels:
            genre_counts[GENRE_NAMES[lbl]] = genre_counts.get(GENRE_NAMES[lbl], 0) + 1
        print(f"[{split}] {len(self.samples)} windows | Genre breakdown: {genre_counts}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        x = torch.tensor(self.samples[idx])
        y = torch.tensor(self.labels[idx], dtype=torch.long)
        return x, y


class VAEEncoder(nn.Module):
    def __init__(self, input_dim=PIANO_KEYS, hidden_dim=HIDDEN_DIM,
                 latent_dim=LATENT, num_layers=2):
        super().__init__()
        self.lstm    = nn.LSTM(input_dim, hidden_dim, num_layers,
                               batch_first=True, dropout=0.2)
        self.fc_mu   = nn.Linear(hidden_dim, latent_dim)
        self.fc_logv = nn.Linear(hidden_dim, latent_dim)

    def forward(self, x):
        _, (h_n, _) = self.lstm(x)
        h       = h_n[-1]
        mu      = self.fc_mu(h)
        log_var = self.fc_logv(h)
        return mu, log_var


class VAEDecoder(nn.Module):
    def __init__(self, latent_dim=LATENT, hidden_dim=HIDDEN_DIM,
                 output_dim=PIANO_KEYS, seq_len=SEQ_LEN, num_layers=2):
        super().__init__()
        self.seq_len    = seq_len
        self.latent_dim = latent_dim
        self.input_proj = nn.Linear(latent_dim, hidden_dim)
        self.lstm       = nn.LSTM(hidden_dim + latent_dim, hidden_dim, num_layers,
                                   batch_first=True, dropout=0.2)
        self.out        = nn.Linear(hidden_dim, output_dim)

    def forward(self, z):
        h_seed  = self.input_proj(z)
        z_rep   = z.unsqueeze(1).repeat(1, self.seq_len, 1)
        lstm_in = torch.cat([
            h_seed.unsqueeze(1).repeat(1, self.seq_len, 1),
            z_rep
        ], dim=-1)
        out, _ = self.lstm(lstm_in)
        return self.out(out)


class MusicVAE(nn.Module):
    def __init__(self, input_dim=PIANO_KEYS, hidden_dim=HIDDEN_DIM,
                 latent_dim=LATENT, seq_len=SEQ_LEN, num_layers=2):
        super().__init__()
        self.encoder    = VAEEncoder(input_dim, hidden_dim, latent_dim, num_layers)
        self.decoder    = VAEDecoder(latent_dim, hidden_dim, input_dim, seq_len, num_layers)
        self.latent_dim = latent_dim

    def reparameterize(self, mu, log_var):
        std = torch.exp(0.5 * log_var)
        eps = torch.randn_like(std)
        return mu + std * eps

    def forward(self, x):
        mu, log_var = self.encoder(x)
        z     = self.reparameterize(mu, log_var)
        x_hat = self.decoder(z)
        return x_hat, mu, log_var, z

def vae_loss(x_hat_logits, x, mu, log_var, beta=1.0,
             focal_gamma=2.0, pos_weight=20.0):
    bce   = F.binary_cross_entropy_with_logits(
        x_hat_logits, x,
        pos_weight=torch.tensor(pos_weight, device=x_hat_logits.device),
        reduction='none'
    )
    probs = torch.sigmoid(x_hat_logits)
    p_t   = probs * x + (1 - probs) * (1 - x)
    recon = (((1 - p_t) ** focal_gamma) * bce).mean()
    kl    = -0.5 * torch.mean(1 + log_var - mu.pow(2) - log_var.exp())
    return recon + beta * kl, recon.item(), kl.item()


def kl_annealing_schedule(epoch: int, warmup_epochs: int = WARMUP_EPOCHS,
                           total_epochs: int = EPOCHS) -> float:
    if epoch <= warmup_epochs:
        return 0.0
    ramp = (epoch - warmup_epochs) / max(1, total_epochs - warmup_epochs)
    return min(1.0, ramp)


def train(model, train_loader, val_loader, epochs=EPOCHS,
          lr=1e-3, warmup_epochs=WARMUP_EPOCHS, device=DEVICE):
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    history   = {'total': [], 'recon': [], 'kl': [], 'beta': [],
                 'val_total': [], 'val_recon': [], 'val_kl': []}

    for epoch in range(1, epochs + 1):
        beta = kl_annealing_schedule(epoch, warmup_epochs, epochs)


        model.train()
        tot = rec = kl_sum = 0.0
        for x, _ in train_loader:
            x = x.to(device)
            x_hat, mu, log_var, _ = model(x)
            loss, r, kl = vae_loss(x_hat, x, mu, log_var, beta=beta)
            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot    += loss.item()
            rec    += r
            kl_sum += kl

        n = len(train_loader)
        history['total'].append(tot / n)
        history['recon'].append(rec / n)
        history['kl'].append(kl_sum / n)
        history['beta'].append(beta)


        model.eval()
        vtot = vrec = vkl = 0.0
        with torch.no_grad():
            for x, _ in val_loader:
                x = x.to(device)
                x_hat, mu, log_var, _ = model(x)
                _, r, kl = vae_loss(x_hat, x, mu, log_var, beta=beta)
                vtot += r + beta * kl
                vrec += r
                vkl  += kl
        vn = len(val_loader)
        history['val_total'].append(vtot / vn)
        history['val_recon'].append(vrec / vn)
        history['val_kl'].append(vkl / vn)

        print(f"Epoch {epoch:2d}/{epochs}  β={beta:.2f}  "
              f"Train[Total={tot/n:.4f} Recon={rec/n:.4f} KL={kl_sum/n:.4f}]  "
              f"Val[Recon={vrec/vn:.4f}]")

    return history


def _roll_to_midi(roll_probs: np.ndarray, threshold: float,
                  fs: int, path: str):
    pm    = pretty_midi.PrettyMIDI()
    piano = pretty_midi.Instrument(program=0)
    dt    = 1.0 / fs
    active = {}
    for t, frame in enumerate(roll_probs):
        on = set(np.where(frame > threshold)[0])
        for n in list(set(active) - on):
            start = active.pop(n)
            end   = t * dt
            if end <= start: end = start + dt
            piano.notes.append(pretty_midi.Note(80, int(n) + PIANO_MIN, start, end))
        for n in on - set(active):
            active[n] = t * dt
    for n, s in active.items():
        piano.notes.append(pretty_midi.Note(80, int(n) + PIANO_MIN, s, s + dt))
    pm.instruments.append(piano)
    pm.write(path)
    print(f"  Saved: {path}  ({len(piano.notes)} notes)")


def generate_samples(model, n: int = 8, threshold: float = 0.2,
                     fs: int = FS, out_dir: str = OUT_DIR, device: str = DEVICE):
    model.eval()
    os.makedirs(out_dir, exist_ok=True)
    with torch.no_grad():
        for i in range(n):
            z      = torch.randn(1, model.latent_dim).to(device)
            logits = model.decoder(z)
            probs  = torch.sigmoid(logits).squeeze(0).cpu().numpy()
            _roll_to_midi(probs, threshold, fs,
                          os.path.join(out_dir, f'task2_sample_{i + 1}.mid'))


def latent_interpolation(model, n_steps: int = 8, threshold: float = 0.2,
                          fs: int = FS, out_dir: str = OUT_DIR, device: str = DEVICE):
    model.eval()
    os.makedirs(out_dir, exist_ok=True)
    with torch.no_grad():
        z1     = torch.randn(1, model.latent_dim).to(device)
        z2     = torch.randn(1, model.latent_dim).to(device)
        alphas = np.linspace(0, 1, n_steps)
        for i, alpha in enumerate(alphas):
            z      = (1.0 - alpha) * z1 + alpha * z2
            logits = model.decoder(z)
            probs  = torch.sigmoid(logits).squeeze(0).cpu().numpy()
            _roll_to_midi(probs, threshold, fs,
                          os.path.join(out_dir,
                                       f'task2_interp_{i + 1}_alpha{alpha:.2f}.mid'))
    print("Latent interpolation complete.")


def rhythm_diversity(midi_path: str, quantize_ms: float = 50.0) -> float:
    pm  = pretty_midi.PrettyMIDI(midi_path)
    dur = []
    for inst in pm.instruments:
        for note in inst.notes:
            q = round((note.end - note.start) * 1000 / quantize_ms) * quantize_ms
            dur.append(q)
    return len(set(dur)) / len(dur) if dur else 0.0


def repetition_ratio(midi_path: str, n: int = 4) -> float:
    from collections import Counter
    pm     = pretty_midi.PrettyMIDI(midi_path)
    notes  = sorted([note for inst in pm.instruments for note in inst.notes],
                    key=lambda x: x.start)
    pitches = [note.pitch for note in notes]
    if len(pitches) < n: return 0.0
    ngrams = [tuple(pitches[i:i + n]) for i in range(len(pitches) - n + 1)]
    counts = Counter(ngrams)
    return sum(1 for c in counts.values() if c > 1) / len(ngrams)


def plot_losses(history, save_path):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    axes[0].plot(history['total'],     label='Train total', linewidth=2)
    axes[0].plot(history['val_total'], label='Val total',   linewidth=2, linestyle='--')
    axes[0].set(xlabel='Epoch', ylabel='Loss', title='Total VAE Loss')
    axes[0].legend()
    axes[1].plot(history['recon'], label='Reconstruction', linewidth=2)
    axes[1].plot(history['kl'],    label='KL divergence',  linewidth=2)
    axes[1].set(xlabel='Epoch', ylabel='Loss', title='Recon vs KL Loss')
    axes[1].legend()
    axes[2].plot(history['beta'], color='green', linewidth=2)
    axes[2].set(xlabel='Epoch', ylabel='β value', title='KL Annealing Schedule (β ramp)')
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Loss plots saved: {save_path}")


if __name__ == '__main__':
    os.makedirs(OUT_DIR,  exist_ok=True)
    os.makedirs(PLOT_DIR, exist_ok=True)

    print(f"Device       : {DEVICE}")
    print(f"Epochs       : {EPOCHS}  (warmup={WARMUP_EPOCHS})")
    print(f"SEQ_LEN      : {SEQ_LEN}")
    print(f"Hidden dim   : {HIDDEN_DIM}")
    print(f"Max files    : {MAX_FILES} per split")


    print("\nLoading datasets...")
    train_ds = MAESTROMultiGenreDataset(CSV_PATH, MIDI_ROOT, split='train')
    val_ds   = MAESTROMultiGenreDataset(CSV_PATH, MIDI_ROOT, split='validation')

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                              num_workers=NUM_WORKERS, pin_memory=(DEVICE == 'cuda'))
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=NUM_WORKERS, pin_memory=(DEVICE == 'cuda'))


    model = MusicVAE(input_dim=PIANO_KEYS, hidden_dim=HIDDEN_DIM,
                     latent_dim=LATENT, seq_len=SEQ_LEN)
    print(f"Parameters   : {sum(p.numel() for p in model.parameters()):,}")


    history = train(model, train_loader, val_loader,
                    epochs=EPOCHS, warmup_epochs=WARMUP_EPOCHS, device=DEVICE)


    plot_losses(history, save_path=f'{PLOT_DIR}/loss_curve_task2.png')
    torch.save(model.state_dict(), WEIGHTS)
    print(f"Model weights saved: {WEIGHTS}")


    print("\nGenerating 8 samples...")
    generate_samples(model, n=8, out_dir=OUT_DIR, device=DEVICE)

    print("\nGenerating 8 interpolation samples...")
    latent_interpolation(model, n_steps=8, out_dir=OUT_DIR, device=DEVICE)


    print("\nMetrics on generated samples:")
    for i in range(1, 9):
        p = f'{OUT_DIR}/task2_sample_{i}.mid'
        if os.path.exists(p):
            print(f"  Sample {i}: "
                  f"RhythmDiv={rhythm_diversity(p):.3f}  "
                  f"RepRatio={repetition_ratio(p):.3f}")