# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8SVsXC2a_m9-wxJ83qFaJmR0bYZr3lT
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
import numpy as np
import pretty_midi
import pandas as pd
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt



BASE      = '/content/drive/MyDrive/music-project'
CSV_PATH  = '/content/maestro/maestro-v3.0.0/maestro-v3.0.0.csv'
MIDI_ROOT = '/content/maestro/maestro-v3.0.0'
OUT_DIR   = f'{BASE}/outputs/generated_midis'
PLOT_DIR  = f'{BASE}/outputs/plots'
WEIGHTS   = f'{BASE}/outputs/ae_weights.pt'




PIANO_MIN          = 21     # A0
PIANO_MAX          = 108    # C8
PIANO_KEYS         = PIANO_MAX - PIANO_MIN + 1   # 88
FS                 = 16     # frames per second
SEQ_LEN            = 128    # time steps per window (= 8 seconds at fs=16)
SPARSITY_THRESHOLD = 0.02   # discard windows with < 2% active cells




class FocalLoss(nn.Module):

    def __init__(self, gamma: float = 2.0, pos_weight: float = 20.0):
        super().__init__()
        self.gamma      = gamma
        self.pos_weight = pos_weight

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:

        bce = F.binary_cross_entropy_with_logits(
            logits, targets,
            pos_weight=torch.tensor(self.pos_weight, device=logits.device),
            reduction='none'
        )
        probs  = torch.sigmoid(logits)
        p_t    = probs * targets + (1 - probs) * (1 - targets)
        focal  = ((1 - p_t) ** self.gamma) * bce
        return focal.mean()




class MAESTRODataset(Dataset):


    def __init__(self, csv_path: str, midi_root: str, split: str = 'train',
                 seq_len: int = SEQ_LEN, fs: int = FS):
        self.seq_len = seq_len
        self.samples = []

        df = pd.read_csv(csv_path)
        df = df[df['split'] == split]

        for _, row in df.iterrows():
            midi_path = os.path.join(midi_root, row['midi_filename'])
            if not os.path.exists(midi_path):
                continue
            try:
                pm   = pretty_midi.PrettyMIDI(midi_path)

                roll = pm.get_piano_roll(fs=fs)[PIANO_MIN:PIANO_MAX + 1, :].T
                roll = (roll > 0).astype(np.float32)


                for start in range(0, len(roll) - seq_len, seq_len):
                    window = roll[start:start + seq_len]

                    if window.mean() >= SPARSITY_THRESHOLD:
                        self.samples.append(window)
            except Exception:
                continue

        print(f"[{split}] Loaded {len(self.samples)} windows from {len(df)} files")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return torch.tensor(self.samples[idx])   # (SEQ_LEN, 88)




class MIDIDirDataset(Dataset):

    def __init__(self, midi_dir: str, seq_len: int = SEQ_LEN, fs: int = FS):
        self.seq_len = seq_len
        self.samples = []

        for fname in sorted(os.listdir(midi_dir)):
            if not fname.endswith(('.mid', '.midi')):
                continue
            try:
                pm   = pretty_midi.PrettyMIDI(os.path.join(midi_dir, fname))
                roll = pm.get_piano_roll(fs=fs)[PIANO_MIN:PIANO_MAX + 1, :].T
                roll = (roll > 0).astype(np.float32)
                for start in range(0, len(roll) - seq_len, seq_len):
                    window = roll[start:start + seq_len]
                    if window.mean() >= SPARSITY_THRESHOLD:
                        self.samples.append(window)
            except Exception:
                continue

        print(f"[dir] Loaded {len(self.samples)} windows from {midi_dir}")

    def get_splits(self, val_fraction: float = 0.1):

        n     = len(self.samples)
        n_val = int(n * val_fraction)
        val_idx   = list(range(n_val))
        train_idx = list(range(n_val, n))
        return Subset(self, train_idx), Subset(self, val_idx)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return torch.tensor(self.samples[idx])




class LSTMEncoder(nn.Module):

    def __init__(self, input_dim=PIANO_KEYS, hidden_dim=256,
                 latent_dim=64, num_layers=2):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers,
                            batch_first=True, dropout=0.2)
        self.fc   = nn.Linear(hidden_dim, latent_dim)

    def forward(self, x):
        # x: (B, T, 88)
        _, (h_n, _) = self.lstm(x)
        # h_n: (num_layers, B, hidden) → take LAST layer's hidden state
        z = self.fc(h_n[-1])          # (B, latent_dim)
        return z


class LSTMDecoder(nn.Module):

    def __init__(self, latent_dim=64, hidden_dim=256, output_dim=PIANO_KEYS,
                 seq_len=SEQ_LEN, num_layers=2):
        super().__init__()
        self.seq_len    = seq_len
        self.latent_dim = latent_dim

        self.input_proj = nn.Linear(latent_dim, hidden_dim)
        # LSTM input = projected z (hidden_dim) concatenated with raw z (latent_dim)
        self.lstm       = nn.LSTM(hidden_dim + latent_dim, hidden_dim, num_layers,
                                   batch_first=True, dropout=0.2)
        self.out        = nn.Linear(hidden_dim, output_dim)

    def forward(self, z):
        # z: (B, latent_dim)
        B       = z.size(0)
        h_seed  = self.input_proj(z)                             # (B, hidden_dim)
        z_rep   = z.unsqueeze(1).repeat(1, self.seq_len, 1)     # (B, T, latent_dim)
        lstm_in = torch.cat([
            h_seed.unsqueeze(1).repeat(1, self.seq_len, 1),     # (B, T, hidden_dim)
            z_rep                                                 # (B, T, latent_dim)
        ], dim=-1)                                               # (B, T, hidden+latent)
        out, _ = self.lstm(lstm_in)
        return self.out(out)    # (B, T, 88) — raw logits


class LSTMAutoencoder(nn.Module):
    def __init__(self, input_dim=PIANO_KEYS, hidden_dim=256,
                 latent_dim=64, seq_len=SEQ_LEN, num_layers=2):
        super().__init__()
        self.encoder    = LSTMEncoder(input_dim, hidden_dim, latent_dim, num_layers)
        self.decoder    = LSTMDecoder(latent_dim, hidden_dim, input_dim, seq_len, num_layers)
        self.latent_dim = latent_dim

    def forward(self, x):
        z     = self.encoder(x)      # z = f_φ(X)
        x_hat = self.decoder(z)      # X̂ = g_θ(z)  — raw logits
        return x_hat, z




def train(model, train_loader, val_loader, epochs=50, lr=1e-3, device='cpu'):

    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = FocalLoss(gamma=2.0, pos_weight=20.0)

    train_losses = []
    val_losses   = []

    for epoch in range(1, epochs + 1):

        model.train()
        epoch_loss = 0.0
        for batch in train_loader:
            x = batch.to(device)                    # (B, T, 88)
            x_hat, _ = model(x)                     # raw logits (B, T, 88)
            loss = criterion(x_hat, x)

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_loss += loss.item()

        avg_train = epoch_loss / len(train_loader)
        train_losses.append(avg_train)


        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for batch in val_loader:
                x = batch.to(device)
                x_hat, _ = model(x)
                val_loss += criterion(x_hat, x).item()
        avg_val = val_loss / len(val_loader)
        val_losses.append(avg_val)

        if epoch % 10 == 0:
            print(f"Epoch {epoch:3d}/{epochs}  "
                  f"Train: {avg_train:.4f}  Val: {avg_val:.4f}")

    return train_losses, val_losses



def generate_midi(model, latent_dim=64, threshold=0.2,
                  fs=FS, out_path='generated.mid', device='cpu'):

    model.eval()
    with torch.no_grad():
        z      = torch.randn(1, latent_dim).to(device)
        logits = model.decoder(z)                            # (1, T, 88)
        probs  = torch.sigmoid(logits).squeeze(0).cpu().numpy()  # (T, 88)

    dt     = 1.0 / fs
    pm     = pretty_midi.PrettyMIDI()
    piano  = pretty_midi.Instrument(program=0)
    active = {}

    for t, frame in enumerate(probs):
        notes_on = set(np.where(frame > threshold)[0])

        for n in list(set(active) - notes_on):
            start = active.pop(n)
            end   = t * dt

            if end <= start:
                end = start + dt
            piano.notes.append(pretty_midi.Note(
                velocity=80,
                pitch=int(n) + PIANO_MIN,
                start=start,
                end=end
            ))

        for n in notes_on - set(active):
            active[n] = t * dt


    total_time = len(probs) * dt
    for n, start in active.items():
        piano.notes.append(pretty_midi.Note(
            velocity=80,
            pitch=int(n) + PIANO_MIN,
            start=start,
            end=start + dt
        ))

    pm.instruments.append(piano)

    if len(piano.notes) < 10:
        print(f"WARNING: Only {len(piano.notes)} notes generated — try lower threshold")
    pm.write(out_path)
    print(f"Saved: {out_path}  ({len(piano.notes)} notes, {total_time:.1f}s)")
    return len(piano.notes)




def pitch_histogram_similarity(midi_path1: str, midi_path2: str) -> float:

    def pitch_class_dist(path):
        pm   = pretty_midi.PrettyMIDI(path)
        hist = np.zeros(12)
        for inst in pm.instruments:
            for note in inst.notes:
                hist[note.pitch % 12] += 1
        total = hist.sum()
        return hist / (total + 1e-8)

    p = pitch_class_dist(midi_path1)
    q = pitch_class_dist(midi_path2)
    return float(np.abs(p - q).sum())


def rhythm_diversity(midi_path: str, quantize_ms: float = 50.0) -> float:

    pm        = pretty_midi.PrettyMIDI(midi_path)
    durations = []
    for inst in pm.instruments:
        for note in inst.notes:
            dur_ms    = (note.end - note.start) * 1000
            quantized = round(dur_ms / quantize_ms) * quantize_ms
            durations.append(quantized)
    if not durations:
        return 0.0
    return len(set(durations)) / len(durations)


def repetition_ratio(midi_path: str, n: int = 4) -> float:

    from collections import Counter
    pm    = pretty_midi.PrettyMIDI(midi_path)
    notes = []
    for inst in pm.instruments:
        notes.extend(inst.notes)
    notes.sort(key=lambda x: x.start)
    pitches = [note.pitch for note in notes]

    if len(pitches) < n:
        return 0.0

    ngrams   = [tuple(pitches[i:i + n]) for i in range(len(pitches) - n + 1)]
    counts   = Counter(ngrams)
    repeated = sum(1 for c in counts.values() if c > 1)
    return repeated / len(ngrams)




def plot_loss(train_losses, val_losses, save_path):
    plt.figure(figsize=(9, 4))
    plt.plot(train_losses, linewidth=2, label='Train loss')
    plt.plot(val_losses,   linewidth=2, linestyle='--', label='Validation loss')
    plt.xlabel('Epoch')
    plt.ylabel('Focal Loss')
    plt.title('Task 1 — LSTM Autoencoder Training & Validation Loss')
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Loss curve saved: {save_path}")



if __name__ == '__main__':

    LATENT = 64
    EPOCHS = 50
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'


    os.makedirs(OUT_DIR,  exist_ok=True)
    os.makedirs(PLOT_DIR, exist_ok=True)

    print(f"Training on device: {DEVICE}")
    print(f"CSV path:   {CSV_PATH}")
    print(f"MIDI root:  {MIDI_ROOT}")
    print(f"Output dir: {OUT_DIR}")


    print("Loading dataset...")
    train_ds = MAESTRODataset(CSV_PATH, MIDI_ROOT, split='train')
    val_ds   = MAESTRODataset(CSV_PATH, MIDI_ROOT, split='validation')

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=0)


    model = LSTMAutoencoder(
        input_dim=PIANO_KEYS,
        hidden_dim=256,
        latent_dim=LATENT,
        seq_len=SEQ_LEN
    )
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")


    train_losses, val_losses = train(model, train_loader, val_loader,
                                      epochs=EPOCHS, device=DEVICE)


    plot_loss(train_losses, val_losses,
              save_path=f'{PLOT_DIR}/loss_curve_task1.png')


    torch.save(model.state_dict(), WEIGHTS)
    print(f"Model weights saved: {WEIGHTS}")


    print("\nGenerating 5 MIDI samples...")
    for i in range(5):
        out_path = f'{OUT_DIR}/task1_sample_{i + 1}.mid'
        n_notes  = generate_midi(
            model, latent_dim=LATENT, threshold=0.2,
            out_path=out_path, device=DEVICE
        )
        if n_notes < 50:
            print(f"  Sample {i + 1}: only {n_notes} notes — try threshold=0.15")


    print("\nMetrics on generated samples:")
    for i in range(1, 6):
        gen_path = f'{OUT_DIR}/task1_sample_{i}.mid'
        if os.path.exists(gen_path):
            rd = rhythm_diversity(gen_path)
            rr = repetition_ratio(gen_path)
            print(f"  Sample {i}: Rhythm Diversity={rd:.3f}  Repetition Ratio={rr:.3f}")

    print("\nTask 1 complete! Check your Google Drive music-project/outputs/ folder.")